server:
  port: 8090
  
  servlet:
    contextPath: /test
    
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/world?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root

resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 5 # 최대 재시도 수
        waitDuration: 5000  # 재시도 사이에 고정된 시간 [ms]
        #retryExceptions:
        #  - org.springframework.web.client.HttpServerErrorException
        #  - java.io.IOException
        #ignoreExceptions:
        #  - java.util.NoSuchElementException
    instances:
      retry-test-3000: # retry name
        baseConfig: default # 기본 config 지정 (Ex-retry.configs.{default})
        waitDuration: 3000
      retry-db-select-4000:
        baseConfig: default
        waitDuration: 4000
      retry-db-select-5000:
        baseConfig: default
        waitDuration: 5000
  circuitbreaker:
    configs:
      default:  # 기본 config 명
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 50 # 실패 확률
        minimumNumberOfCalls: 3  # 최소한 호출을 10번을 기록해야 실패 비율을 계산할 수 있다.
        slowCallRateThreshold: 100 
        slowCallDurationThreshold: 60000
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 1 # half open상태일때 open/close를 판단할 최소 호출횟수
        waitDurationInOpenState: 10s  # 서킷의 상태가 Open 에서 Half-open 으로 변경되기전에 Circuit Break가 기다리는 시간 [s]
    instances:
      circuit-test-70000: # circuitbreaker name
        baseConfig: default # 기본 config 지정 (Ex-circuitbreaker.configs.{default})
        slowCallDurationThreshold: 70000 # 응답시간이 느린것으로 판단할 기준 시간 [ms]
      circuit-db-select-200:
        baseConfig: default
        slowCallDurationThreshold: 200
      circuit-db-select-300:
        baseConfig: default
        slowCallDurationThreshold: 300

management:
  endpoints:
    web:
      exposure:
        include:
          - "*" # 테스트를 위해 actuator 전체 노출

  health:
    circuitbreakers:
      enabled: true # circuitbreakers 정보 노출